# Generated by Django 4.2.23 on 2025-08-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warranty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyCultureRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("unit_serial_number", models.CharField(max_length=100, unique=True)),
                ("ums_sn", models.CharField(blank=True, max_length=100, null=True)),
                ("audit_date", models.DateField()),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "tm_device_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExampleModel",
        ),
    ]
