# Generated by Django 4.2.23 on 2025-08-18 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("warranty", "0003_rename_fields_and_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetyculturerecord",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="safetyculturerecord",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="safetyculturerecord",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="model_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="warranty_expiry",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
