# Generated by Django 4.2.23 on 2025-08-26 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warranty", "0004_safetyculturerecord_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="model_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="tm_device_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="ums_sn",
            field=models.CharField(
                blank=True,
                default=3,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}-\\d{4}$", "UMS SN must be in xxxx-xxxx format"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="unit_sn",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        "^IG1[A-Z0-9]+$", "Unit Serial Number must start with IG1"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
