# Generated by Django 4.2.23 on 2025-08-26 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warranty", "0005_alter_safetyculturerecord_model_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetyculturerecord",
            name="ums_sn",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}-\\d{4}$", "UMS SN must be in xxxx-xxxx format"
                    )
                ],
            ),
        ),
    ]
