# Generated by Django 4.2.26 on 2025-12-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0006_alter_safetyculturerecord_ums_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantySyncState',
            fields=[
                ('id', models.CharField(default='default', max_length=32, primary_key=True, serialize=False)),
                ('last_audit_id', models.CharField(blank=True, db_index=True, help_text='Cursor of the last processed SafetyCulture audit_id for incremental sync.', max_length=64, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warranty Sync State',
                'verbose_name_plural': 'Warranty Sync State',
            },
        ),
        migrations.AlterModelOptions(
            name='safetyculturerecord',
            options={'ordering': ['-audit_date', 'unit_sn'], 'verbose_name': 'SafetyCulture Record', 'verbose_name_plural': 'SafetyCulture Records'},
        ),
        migrations.AddField(
            model_name='safetyculturerecord',
            name='audit_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='safetyculturerecord',
            name='sc_modified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='safetyculturerecord',
            index=models.Index(fields=['audit_date'], name='warranty_sa_audit_d_1c1acc_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyculturerecord',
            index=models.Index(fields=['model_number'], name='warranty_sa_model_n_c463fa_idx'),
        ),
    ]
